
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Fri Feb 02 19:20:01 CET 2024
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int DIVIDE = 19;
  public static final int CHAR = 46;
  public static final int CONST = 4;
  public static final int ASSIGNMENT = 29;
  public static final int NAMESPACE = 13;
  public static final int RIGHT_SQUARE_BRACKET = 40;
  public static final int NOT_EQUAL = 22;
  public static final int REM = 20;
  public static final int GREATER = 23;
  public static final int CONTINUE = 10;
  public static final int LESS = 25;
  public static final int FOR = 11;
  public static final int MINUS = 17;
  public static final int STATIC = 12;
  public static final int AND = 27;
  public static final int OR = 28;
  public static final int BOOL = 45;
  public static final int COMMA = 34;
  public static final int INC = 30;
  public static final int DBLCOLON = 36;
  public static final int LESS_EQUAL = 26;
  public static final int PLUS = 16;
  public static final int MULTIPLY = 18;
  public static final int LEFT_CURLY_BRACKET = 41;
  public static final int IF = 14;
  public static final int DOT = 35;
  public static final int LEFT_ROUND_BRACKET = 37;
  public static final int EOF = 0;
  public static final int RETURN = 8;
  public static final int EQUAL = 21;
  public static final int GREATER_EQUAL = 24;
  public static final int LEFT_SQUARE_BRACKET = 39;
  public static final int NEW = 5;
  public static final int error = 1;
  public static final int PROGRAM = 2;
  public static final int SEMI_COLON = 32;
  public static final int NUMBER = 44;
  public static final int IDENT = 43;
  public static final int BREAK = 3;
  public static final int VOID = 9;
  public static final int COLON = 33;
  public static final int ELSE = 15;
  public static final int READ = 7;
  public static final int DEC = 31;
  public static final int RIGHT_CURLY_BRACKET = 42;
  public static final int PRINT = 6;
  public static final int RIGHT_ROUND_BRACKET = 38;
}

